[package]
name = "forge"
version = "1.0.0-beta.4"
edition = "2024"
authors = ["ronakgh97@gmail.com"]
description = "An Experimental AI Loop/Network Library."
license = "MIT"
repository = "https://github.com/ronakgh97/forge"
homepage = "https://github.com/ronakgh97/forge"
readme = "README.md"

[lib]
name = "forge"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
async-trait = "0.1.91"
anyhow = "1.0.104"

[dev-dependencies]
rand = "0.10.2"
