[package]
name = "forge"
version = "0.1.0"
edition = "2024"
authors = ["ronakgh97@gmail.com"]
description = "A Low level, Opinionated, AI-Agent library."
license = "MIT"
repository = "https:/github.com/ronakgh97/forge"
homepage = "https:/github.com/ronakgh97/forge"
documentation = "https:/github.com/ronakgh97/forge/master/README.md"

[lib]
name = "forge"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.89"
tokio = { version = "1.49.0", features = ["full"] }
futures-util = "0.3.31"
eventsource-stream = "0.2.3"
reqwest = { version = "0.13.1", features = ["json", "stream"] }
serde = "1.0.228"
serde_json = "1.0.149"
colored = "3.0.0"
anyhow = "1.0.100"
toml = "0.9.8"
base64 = "0.22.1"
