[package]
name = "forge"
version = "0.1.0"
edition = "2024"
authors = ["ronakgh97@gmail.com"]
description = "A Opinionated AI API library."
license = "MIT"
repository = "https:/github.com/ronakgh97/forge"
homepage = "https:/github.com/ronakgh97/forge"
documentation = "https:/github.com/ronakgh97/forge/master/README.md"

[lib]
name = "forge"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.52.3", features = ["full"] }
async-trait = "0.1.89"
futures-util = "0.3.32"
eventsource-stream = "0.2.3"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
colored = "3.1.1"
anyhow = "1.0.102"
rand = "0.10.1"
base64 = "0.22.1"