use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Main request structure for the /chat/completions endpoint
#[derive(Debug, Serialize, Deserialize, Clone)]
pub(crate) struct CompletionRequest {
    pub model: String,
    pub messages: Vec<Message>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    pub temperature: f32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>, // TODO; properly implement this
}

/// Main response structure for the /chat/completions endpoint, includes the generated message(s) and metadata
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct CompletionResponse {
    pub id: String,
    pub created: u64,
    pub model: String,
    pub choices: Vec<CompletionChoice>,
}

/// Represents a single choice in the completion response, includes the index of the choice and the final generated message
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct CompletionChoice {
    pub index: u32,
    pub message: Message,
}

/// Represents a single message in the conversation, can contain either simple text content or multi-content (text + images)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Message {
    pub role: Role,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Role of the message sender, can be system, user, assistant, or tool
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

/// Represents a tool/function definition included in the request, called by the model
#[derive(Debug, Serialize, Deserialize, Clone)]
pub(crate) struct Tool {
    pub r#type: String,
    pub function: FunctionDefinition,
}

/// Generated by the model when it decides to call a tool/function, includes the function name and arguments (as a JSON string)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolCall {
    pub id: String,
    pub r#type: String,
    pub function: FunctionCall,
}

/// Represents the actual function call made by the model, includes the function name and arguments (as a JSON string)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String, // JSON string
}

/// Represents the definition of a function/tool that the model can call, including its name, description, and parameters (as a JSON Schema)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub(crate) struct FunctionDefinition {
    pub name: String,
    pub description: String,
    pub parameters: Value, // JSON Schema
}

#[test]
fn test_message_content_serialization() -> anyhow::Result<()> {
    let msg_text = Message {
        role: Role::User,
        content: Some("Hello, world!".to_string()),
        tool_calls: None,
        tool_call_id: None,
        name: None,
    };
    let json_text = serde_json::to_string(&msg_text)?;
    assert!(json_text.contains(r#""content":"Hello, world!""#));

    let api_response = r#"{
            "role": "assistant",
            "content": "This is the AI response"
        }"#;
    let msg_response: Message = serde_json::from_str(api_response)?;
    assert_eq!(
        msg_response.content,
        Some("This is the AI response".to_string())
    );
    assert_eq!(msg_response.role, Role::Assistant);

    let user_message = r#"{
            "role": "user",
            "content": "What is the weather?"
        }"#;
    let msg_user: Message = serde_json::from_str(user_message)?;
    assert_eq!(msg_user.content, Some("What is the weather?".to_string()));

    Ok(())
}
